[2025-04-29T19:42:38.741+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-29T19:42:38.766+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-28T00:00:00+00:00 [queued]>
[2025-04-29T19:42:38.778+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-28T00:00:00+00:00 [queued]>
[2025-04-29T19:42:38.778+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-04-29T19:42:38.794+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-28 00:00:00+00:00
[2025-04-29T19:42:38.801+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-28T00:00:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpqvz8euxo']
[2025-04-29T19:42:38.803+0000] {standard_task_runner.py:105} INFO - Job 151: Subtask load_task
[2025-04-29T19:42:38.804+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T19:42:38.805+0000] {standard_task_runner.py:72} INFO - Started process 184 to run task
[2025-04-29T19:42:38.857+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-28T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-04-29T19:42:38.952+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T00:00:00+00:00'
[2025-04-29T19:42:38.953+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-29T19:42:38.983+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-29', 13.1, 26.1, 0.0, 1], ['2025-04-30', 15.2, 28.0, 0.0, 1], ['2025-05-01', 17.0, 29.3, 0.0, 3], ['2025-05-02', 16.0, 27.6, 0.1, 3], ['2025-05-03', 15.7, 25.5, 7.8, 95], ['2025-05-04', 12.1, 17.2, 0.0, 61], ['2025-05-05', 6.4, 16.6, 0.0, 3]]
[2025-04-29T19:42:38.996+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-29T19:42:39.009+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-29T19:42:39.010+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-28T00:00:00+00:00, execution_date=20250428T000000, start_date=20250429T194238, end_date=20250429T194239
[2025-04-29T19:42:39.062+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-29T19:42:39.091+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T19:42:39.093+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
