[2025-04-17T20:58:49.740+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T20:58:49.766+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-16T00:00:00+00:00 [queued]>
[2025-04-17T20:58:49.783+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-16T00:00:00+00:00 [queued]>
[2025-04-17T20:58:49.784+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-04-17T20:58:49.808+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-16 00:00:00+00:00
[2025-04-17T20:58:49.818+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-16T00:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpyieecj0b']
[2025-04-17T20:58:49.821+0000] {standard_task_runner.py:105} INFO - Job 92: Subtask load_task
[2025-04-17T20:58:49.822+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=176) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-17T20:58:49.823+0000] {standard_task_runner.py:72} INFO - Started process 177 to run task
[2025-04-17T20:58:49.877+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-16T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-04-17T20:58:49.990+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-16T00:00:00+00:00'
[2025-04-17T20:58:49.992+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-17T20:58:50.027+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-17', 7.8, 16.3, 0.0, 3], ['2025-04-18', 6.7, 17.7, 0.0, 3], ['2025-04-19', 9.2, 19.3, 2.2, 61], ['2025-04-20', 12.6, 19.2, 0.6, 80], ['2025-04-21', 9.6, 18.4, 0.9, 80], ['2025-04-22', 10.6, 18.5, 0.3, 3], ['2025-04-23', 10.1, 13.7, 10.8, 80]]
[2025-04-17T20:58:50.043+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-17T20:58:50.059+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-17T20:58:50.060+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-16T00:00:00+00:00, execution_date=20250416T000000, start_date=20250417T205849, end_date=20250417T205850
[2025-04-17T20:58:50.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-17T20:58:50.141+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T20:58:50.143+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
