[2025-04-30T17:02:57.103+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-30T17:02:57.130+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-29T00:00:00+00:00 [queued]>
[2025-04-30T17:02:57.143+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-29T00:00:00+00:00 [queued]>
[2025-04-30T17:02:57.144+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-04-30T17:02:57.160+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-29 00:00:00+00:00
[2025-04-30T17:02:57.168+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-29T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpj_a_7l8r']
[2025-04-30T17:02:57.170+0000] {standard_task_runner.py:105} INFO - Job 156: Subtask load_task
[2025-04-30T17:02:57.171+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=177) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-30T17:02:57.172+0000] {standard_task_runner.py:72} INFO - Started process 178 to run task
[2025-04-30T17:02:57.225+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-29T00:00:00+00:00 [running]> on host e5bea2914fd7
[2025-04-30T17:02:57.328+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T00:00:00+00:00'
[2025-04-30T17:02:57.329+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-30T17:02:57.357+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-30', 14.1, 28.3, 0.0, 2], ['2025-05-01', 16.5, 29.2, 0.0, 3], ['2025-05-02', 17.8, 28.6, 0.0, 3], ['2025-05-03', 17.9, 22.8, 1.4, 80], ['2025-05-04', 12.0, 17.4, 1.2, 3], ['2025-05-05', 6.4, 14.1, 0.0, 3], ['2025-05-06', 6.4, 16.4, 0.0, 3]]
[2025-04-30T17:02:57.368+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-30T17:02:57.380+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-30T17:02:57.381+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-29T00:00:00+00:00, execution_date=20250429T000000, start_date=20250430T170257, end_date=20250430T170257
[2025-04-30T17:02:57.428+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-30T17:02:57.447+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-30T17:02:57.449+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
