[2025-04-06T20:17:28.870+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T20:17:28.898+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T20:17:28.910+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T20:17:28.911+0000] {taskinstance.py:2867} INFO - Starting attempt 7 of 10
[2025-04-06T20:17:28.926+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-05 00:00:00+00:00
[2025-04-06T20:17:28.936+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpxe3eykth']
[2025-04-06T20:17:28.940+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask load_task
[2025-04-06T20:17:28.940+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=178) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-06T20:17:28.941+0000] {standard_task_runner.py:72} INFO - Started process 179 to run task
[2025-04-06T20:17:29.004+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-05T00:00:00+00:00 [running]> on host c53269dc4062
[2025-04-06T20:17:29.108+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-06T20:17:29.109+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T20:17:29.137+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-06', 9.9, 18.8, 0.0, 3], ['2025-04-07', 6.1, 17.0, 0.0, 1], ['2025-04-08', 7.3, 18.1, 0.0, 3], ['2025-04-09', 6.3, 17.8, 0.0, 1], ['2025-04-10', 6.0, 18.6, 0.0, 1], ['2025-04-11', 6.6, 21.0, 0.0, 0], ['2025-04-12', 7.7, 22.7, 0.0, 3]]
[2025-04-06T20:17:29.148+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-06T20:17:29.161+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T20:17:29.163+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-05T00:00:00+00:00, execution_date=20250405T000000, start_date=20250406T201728, end_date=20250406T201729
[2025-04-06T20:17:29.238+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-06T20:17:29.257+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T20:17:29.259+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
