[2025-04-06T20:16:57.807+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T20:16:57.833+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T20:16:57.846+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_task scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T20:16:57.847+0000] {taskinstance.py:2867} INFO - Starting attempt 6 of 9
[2025-04-06T20:16:57.862+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_task> on 2025-04-05 00:00:00+00:00
[2025-04-06T20:16:57.872+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_task', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpbtyaggtc']
[2025-04-06T20:16:57.874+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask load_task
[2025-04-06T20:16:57.876+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=168) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-06T20:16:57.878+0000] {standard_task_runner.py:72} INFO - Started process 171 to run task
[2025-04-06T20:16:57.930+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_task scheduled__2025-04-05T00:00:00+00:00 [running]> on host c53269dc4062
[2025-04-06T20:16:58.035+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-06T20:16:58.036+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T20:16:58.086+0000] {etl_pipeline.py:45} INFO - Données à charger : [['2025-04-06', 9.9, 18.8, 0.0, 3], ['2025-04-07', 6.1, 17.0, 0.0, 1], ['2025-04-08', 7.3, 18.1, 0.0, 3], ['2025-04-09', 6.3, 17.8, 0.0, 1], ['2025-04-10', 6.0, 18.6, 0.0, 1], ['2025-04-11', 6.6, 21.0, 0.0, 0], ['2025-04-12', 7.7, 22.7, 0.0, 3]]
[2025-04-06T20:16:58.098+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-06T20:16:58.112+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T20:16:58.112+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_task, run_id=scheduled__2025-04-05T00:00:00+00:00, execution_date=20250405T000000, start_date=20250406T201657, end_date=20250406T201658
[2025-04-06T20:16:58.174+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-06T20:16:58.194+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T20:16:58.196+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
